baseURL = "https://karinasoares.me/"
languageCode = "pt-BR"
title = "Karina Soares dos Santos"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:title/"

[params]
  avatar = "img/karina.png"
  author = "Karina Soares dos Santos"
  description = "Este é o meu site pessoal e nele eu quero compartilhar um pouco dos meus projetos e praticar a escrita criativa ou técnica, ainda não sei."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = [] 

[params.social]
  Github        = "karysoares"
  Email         = "karinasoares@tuta.io"
  Twitter       = "Karysoares"
  LinkedIn      = "soareskarina"
  Medium        = "karysoaress"
  Telegram      = "Karysoares"


## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
